### PR TITLE
Feature/is my address

### PR DESCRIPTION
**Pull request by EvgenKor**
The feature introduce function `ZkBobClient.isMyAddress` which returns `true` when passed shieldedAddress belongs to the current account

History records now supports `isLoopback` flag for every direction

### CODE REVIEW

**Comment by AllFi** [comment]
🔁 and "MYSELF" look a bit redundant to me. All changes look correct but we'll need to be careful when we'll merge it with #51.

**Review by AllFi — APPROVED** [review]

**Comment by EvgenKor** [comment]
> 🔁 and "MYSELF" look a bit redundant to me

It's just for extra highlighting. I think to remove the character 🔁

> we'll need to be careful when we'll merge it with https://github.com/zkBob/zkbob-client-js/pull/51.

Of course, I will manually merge them with additional code changes

**Review by AllFi — APPROVED** [review]
Looks good to me.

**Review by LyzeOfKiel — APPROVED** [review]

**Comment by akolotov** [comment]
@EvgenKor please resolve the merge confict

**Pull request merged**
