### PR TITLE
Feature/partial tree

### PR DESCRIPTION
**Pull request by EvgenKor**
**Supporting for partial tree sync, state rollbacking and wiping, self-healing approach to restore corrupted state**
- Integrated `birthindex` optional parameter  in `ClientConfig` (which is used in `ZkBobClient` initialization). If it was set during init process, the state will sync from the specified index (need relayer support for siblings). If `birthindex < 0` - the library will convert it to the actual tree `next_index - 128` (new account case)
- Added support for specified index in routines `ZkBobClient::{getLocalState, getPoolState}`
- `ZkBobClient::{getLeftSiblings, getFirstIndex}` - for testing purposes on the console tool
- `ZkBobClient::{rollbackState, cleanState}` - to support self-healing
- history storage rollback implemented as well
- requesting partial tree if `birthindex` was specified. Partial tree sync conditions:
  - the pool should contain greater than PARTIAL_TREE_USAGE_THRESHOLD txs (500 currently)
  - the client birthindex should exist
  - relayer should return siblings for birthindex with correct format (`/siblings?index=...` method, format was discussed with @LyzeOfKiel )
- local tree root verify and restore routines. Self-healing logic (occured after the each state updating):
  - we look for the current state's `next_index` value and last verified index. In case of equality - skip the checks
  - get local root and compare it with the one from pool contract (direct web3 request)
  - if roots are match each other - save current `next_index` as last verified index and finish check routine
  - if roots are different - attempt to restore tree:
    - rollback to the last verified index and start state sync again (number of possible rollbacks are limited by CORRUPT_STATE_ROLLBACK_ATTEMPTS constant: 2 currently)
    - wipe all user state and retry sync (number of possible rollbacks are limited by CORRUPT_STATE_WIPE_ATTEMPTS constant: 5 currently). After the first wiping in case of state unrestored - begin to ignore `birthindex` in the synchronization process
    - throw InternalError('Unable to synchronize pool state') in case of exhausting all rollback/wipes attempts

Depends on https://github.com/zkBob/libzkbob-rs/pull/33 and https://github.com/zkBob/zeropool-relayer/pull/113

The library can be tested along [libzkbob-rs](https://github.com/zkBob/libzkbob-rs/tree/feature/partial_tree) library and [zkbob-console](https://github.com/zkBob/zkbob-console/tree/feature/partial_tree) tool with associated branches.

### CODE REVIEW

**Comment by EvgenKor** [comment]
Build with Actions was failed due to `libzkbob-rs-wasm-web` dependency is currently corrupted (because it wasn;t published yet)

**Review by AllFi — APPROVED** [review]
It looks good to me but we'll need to merge it carefully with #65.

**Review by r0wdy1 — APPROVED** [review]
lgtm

**Comment by akolotov** [comment]
https://github.com/zkBob/zeropool-relayer/pull/113 has been merged. This PR can be tested now together with the new relayer. @EvgenKor could you post here results of the testing so we can merge the PR. Thanks!

**Pull request merged**
